name: mobile
on:
  push:
    paths:
      - 'packages/mobile/**'
      - '.github/workflows/mobile.yaml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn mobile install
