name: mobile
on:
  push:
    paths:
      - 'packages/mobile/**'
      - '.github/workflows/mobile.yaml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn mobile install

      - name: Install expo cli
        run: npm install --global expo-cli

      - name: Login to expo via cli
        run: expo login --username ${{ secrets.EXPO_USER_NAME }} --password ${{ secrets.EXPO_PASSWORD }}

      - name: Codegen from graphql schema
        run: yarn mobile codegen

      - name: Build and deploy
        run: yarn mobile deploy
env:
  HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
  HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
  AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
